### PR TITLE
Parent

### PR DESCRIPTION
**Pull request by simontegg**

### CODE REVIEW

**Comment by simontegg** [comment]
@ahdinosaur Could probably deploy this. Tags swap on route changes but you cant interact with them. 
Can't navigate to some people. I also get a weird bug where navigation fails (cola throws an error) on first load but works on subequent loads. Can you check if you get this?

I've used `reflux.js` and `minimal-immutable` to manage complexity and unidirectionality of cola updating. Worked well.

**Comment by ahdinosaur** [comment]
@simontegg sweet! :pear: is it possible to rebase or merge this with master?

**Comment by ahdinosaur** [comment]
wow @simontegg, this is incredible. :cake:

**Comment by simontegg** [comment]
@ahdinosaur Ok I've rebased then pull merged.

**Comment by ahdinosaur** [comment]
woot!

**Pull request merged**
