### PR TITLE
separate data into remote repo, make data more accessible to edit

### LINKED ISSUE #10: user updates to YAML data causes app re-deploy
aka continuous integration via GitHub

### LINKED ISSUE #12: relationship YAML data is easier to edit
there's no point in having `relationships` data when at this point it can all be derived from the `@id` in the respective `people` data.

`@id` will be of the form `<is>:<relationship>:<has>`

### PR DESCRIPTION
**Pull request by ahdinosaur**
makes it possible for others outside of Enspiral to start using Holodex with their own data, if anyone were so inclined. also lets us poll for data updates over git in an easy way.

close https://github.com/open-app/holodex/issues/10.
close https://github.com/open-app/holodex/issues/12.

### CODE REVIEW

**Comment by ahdinosaur** [comment]
merged and deployed :tada:

**Comment by bhaugen** [comment]
@ahdinosaur - what would we do to use Holodex with our own data? Publish it in github? Or install Holodex and then publish the data in github?

(Sorry if the answer should have been obvious...)

**Comment by simontegg** [comment]
Weve talked about having an  'open-app' version for representing the various teams within open-app. 

The data management might be a bit tricky at first since we're just leveraging off github's interface fr editing. 
Keen to support this!

**Comment by bhaugen** [comment]
When you think you are ready to test, please ping us and we'll be a test case.

We'd like to go a little crazy with this eventually, though. Be able to feed live data to Holodex from our various NRP installations.

**Comment by ahdinosaur** [comment]
@bhaugen to use Holodex with your own data, you'd need to make a repo in the same format as https://github.com/holodex/enspiral-data. this is our stop-gap solution so we can focus on the read-only interface for Holodex. we realize this isn't as accessible as possible, realistically the data might only make sense to a trained admin (like @simontegg and i), but we plan to make some basic documentation soon to describe our data format and how to edit the YAML files to maybe make the data be accessible to a few more people.

**Comment by bhaugen** [comment]
Could it be valnet/nrp-data? Or something else?

And then would we be able to view it from http://holodex.enspiral.info/ ? Or deploy our own instance?

Or would it really be better to wait?

**Comment by ahdinosaur** [comment]
it'd be whatever repo you want and we'd have to deploy another instance (which i'm happy to maintain for you).

or waiting is okay too, we're barely usable at this point.

**Comment by bhaugen** [comment]
I don't want to slow down your progress so we can have some fun (which maintaining another instance might be). What would do you some good? Now or later?

**Comment by ahdinosaur** [comment]
later, once we finish our [0.2 release](https://github.com/open-app/holodex/milestones/0.2%20-%20Read-Only%20Multi-Group%20Madness).

**Pull request merged**
