### PR TITLE
empty mad science stack

### PR DESCRIPTION
**Pull request by ahdinosaur**
plus merging compost commits into master, so we keep our history complete.

/cc @donlewi @locksmithdon

### CODE REVIEW

**Comment by don-smith** [comment]
Is this the most current version of the stack we want to use? Is there a plan to clean up the other branches? What is the next step forward? We want to move forward on the Grad Profile app. Are we thinking that will be a fork of Holodex and we'll just manually keep the stack sync'd across the repos? Sorry for all the questions. I'm just seeking clarity and consensus.

**Comment by ahdinosaur** [comment]
yes, this is the most current version of the stack copied over.

what other branches are you referring to? this is on top the history of most of our previous work, there's a few dead end branches i made a while back, but nothing that is important to keep (except for when i like to take a journey in the past for sentimental value).

next step forward is to build the grads profile app as desired by Ro. i imagine this means we need to work on user stories to become gherkin features. the domain models we'll need are already done, i can update your wiki page with the changes i recommend.

i'm thinking the grad profile app _will be Holodex_, then after we meet the requirements of Ro we can focus on other user stories for what we need as a consulting team, what Enspiral needs as a networks, etc.

happy to answer any and all questions. :)

do we have a timeline

**Comment by ahdinosaur** [comment]
sow, on my phone and accidentally closes pull request.

meant to ask: do we have people and a timeline for when we'll will be working on this? keen to support this as best i can, so excited for this to be happening.

**Comment by don-smith** [comment]
When Dan and I last spoke about team availability and project assignments, we didn't have anyone to start on this work, so we decided we would start on it ourselves since Rohan really doesn't want to wait weeks before someone is freed up. And frankly we don't want to wait either ;) I'm really looking forward to announcing the new Holodex.

**Comment by ahdinosaur** [comment]
sweet as. merging, to keep our previous history while creating a foundation for the new work. /cc @simontegg

**Pull request merged**
