### PR TITLE
Legend widget

### PR DESCRIPTION
**Pull request by simontegg**

### CODE REVIEW

**Comment by simontegg** [comment]
Ok @ahdinosaur try this one out. (pr on data as well)

**Comment by ahdinosaur** [comment]
if we're using `material-ui` can we only require the parts that we actually use? it's a massive increase to our bundle size if we include everything. also btw it's not a dependency in the `package.json` yet.

**Comment by simontegg** [comment]
ok

**Comment by ahdinosaur** [comment]
is it on purpose that there's no legend to the 'subgroup', 'parent-group' relationship? that doesn't match what i expected.

also still can't visualize 'is-member-of' or 'has-member' relationships, as i'd expect, but that's the same as it is now.

**Comment by simontegg** [comment]
The legend-widget is set to only appears for context relationships. Though it could be done as you expect .My sense is that users primarily want to toggle the query on/off for non-context relationships.

**Comment by ahdinosaur** [comment]
maybe that's true about toggling, but there's nothing that describes what i'm seeing if i see orange arrows but no legend to describe what that means.

**Comment by simontegg** [comment]
That's right. The query-tag could have an associated link icon, or the legend widget could be present if links are shown, or the link description could appear on hover or click.

I don't have a high confidence in a particular solution to the above, so the thinking was was to solve one main problem (I want to toggle the links (and their targets) on/off while keeping the query present, where there is large distinction between toggled states.

**Comment by ahdinosaur** [comment]
yeah, i'm happy enough with this as is and keen to see how others react, just giving feedback on my reaction.

**Comment by simontegg** [comment]
fair enough

**Comment by ahdinosaur** [comment]
if https://github.com/holodex/app/commit/a1dc93af9b33ea3572b0e54a0c435e75a9919f38 works, then :+1: from me on merge.

**Comment by ahdinosaur** [comment]
sweet, i'll try and get this deployed tonight.

**Pull request merged**
